const nicheTerms = {
  tattoo: {
    professional: 'Tatuador',
    professionals: 'Tatuadores',
    service: 'Tatuagem',
    services: 'Tatuagens',
    booking: 'Sessão',
    bookings: 'Sessões',
    business: 'Estúdio',
    portfolio: 'Portfólio',
    inventory: 'Suprimentos',
  },
  beauty: {
    professional: 'Profissional',
    professionals: 'Profissionais',
    service: 'Procedimento',
    services: 'Procedimentos',
    booking: 'Agendamento',
    bookings: 'Agendamentos',
    business: 'Salão',
    portfolio: 'Portfólio',
    inventory: 'Produtos',
  },
  barber: {
    professional: 'Barbeiro',
    professionals: 'Barbeiros',
    service: 'Serviço',
    services: 'Serviços',
    booking: 'Agendamento',
    bookings: 'Agendamentos',
    business: 'Barbearia',
    portfolio: 'Galeria',
    inventory: 'Produtos',
  },
  clinic: {
    professional: 'Especialista',
    professionals: 'Especialistas',
    service: 'Procedimento',
    services: 'Procedimentos',
    booking: 'Agendamento',
    bookings: 'Agendamentos',
    business: 'Clínica',
    portfolio: 'Resultados',
    inventory: 'Insumos',
  },
  generic: {
    professional: 'Profissional',
    professionals: 'Profissionais',
    service: 'Serviço',
    services: 'Serviços',
    booking: 'Agendamento',
    bookings: 'Agendamentos',
    business: 'Negócio',
    portfolio: 'Portfólio',
    inventory: 'Estoque',
  },
};

const baseTranslations = {
  admin: 'Administrador',
  artist: 'Profissional',
  dashboard: 'Painel',
  myDashboard: 'Meu painel',
  myAgenda: 'Minha agenda',
  home: 'Início',
  clients: 'Clientes',
  client: 'Cliente',
  clientManagement: 'Gestão de clientes',
  leads: 'Leads',
  leadsManagement: 'Captação de clientes',
  schedule: 'Agenda',
  finance: 'Financeiro',
  inventory: 'Estoque',
  settings: 'Configurações',
  summary: 'Visão geral',
  managementSystem: 'Sistema de gestão',
  system: 'Sistema',
  notifications: 'Notificações',
  noNotifications: 'Nenhuma notificação no momento',
  markAllAsRead: 'Marcar todas como lidas',
  logout: 'Sair',
  total_revenue: 'Faturamento total',
  total_expenses: 'Despesas',
  business_profit: 'Lucro do negócio',
  total_leads: 'Novos leads',
  revenue_performance: 'Desempenho financeiro',
  financial_summary: 'Resumo financeiro',
  gross_revenue: 'Receita bruta',
  gross_revenue_paid: 'Entradas pagas no período',
  gross_revenue_global: 'Faturamento bruto',
  operational_outflows: 'Saídas operacionais',
  net_result: 'Resultado líquido',
  net_global_result: 'Resultado sem comissões',
  active_acquisition: 'Captação em andamento',
  monthly_gross_revenue: 'Evolução mensal do faturamento',
  total_period: 'Total do período',
  stock_alerts: 'Alertas de estoque',
  item_below_min: 'item abaixo do mínimo',
  items_below_min: 'itens abaixo do mínimo',
  view_stock: 'Ver estoque',
  todays_schedule: 'Agenda de hoje',
  no_booking_today: 'Nenhum agendamento para hoje',
  view_all: 'Ver tudo',
  pending: 'Pendente',
  paid: 'Pago',
  completed: 'Concluído',
  confirmed: 'Confirmado',
  statusDepositPaid: 'Sinal pago',
  deposit_paid: 'Sinal pago',
  complete_and_register_payment: 'Concluir e registrar pagamento',
  details: 'Detalhes',
  retained_commissions: 'Comissões retidas',
  professionals_share: 'Repasse dos profissionais',
  total_moved: 'Total movimentado',
  professionals: 'Profissionais',
  appointments: 'Atendimentos',
  date: 'Data',
  type: 'Tipo',
  category: 'Categoria',
  description: 'Descrição',
  value: 'Valor',
  optional: 'Opcional',
  none: 'Nenhum',
  income: 'Entrada',
  expense: 'Saída',
  new_transaction: 'Nova transação',
  register_new_transaction: 'Registrar nova transação',
  description_placeholder: 'Ex.: pagamento de serviço, aluguel, material',
  service: 'Serviço',
  sale: 'Venda',
  workshop: 'Workshop',
  others: 'Outros',
  materials: 'Materiais',
  rent: 'Aluguel',
  utilities: 'Contas fixas',
  maintenance: 'Manutenção',
  marketing: 'Marketing',
  export: 'Exportar',
  export_csv: 'Baixar CSV',
  export_pdf: 'Gerar PDF',
  save_transaction: 'Salvar transação',
  cancel: 'Cancelar',
  professional: 'Profissional',
  payment_method: 'Forma de pagamento',
  period_result: 'Resultado do período',
  after_commissions: 'Após comissões',
  visual_summary: 'Resumo visual',
  margin: 'Margem',
  commissions: 'Comissões',
  result: 'Resultado',
  period_transactions: 'Lançamentos do período',
  this_month: 'Este mês',
  all: 'Tudo',
  no_transactions_found: 'Nenhum lançamento encontrado',
  business_share: 'Parcela do negócio',
  show_details: 'Ver detalhes',
  hide_details: 'Ocultar detalhes',
  completed_bookings: 'Agendamentos concluídos',
  accumulated_commission: 'Comissão acumulada',
  commission: 'Comissão',
  based_on_filter: 'Baseado no filtro',
  all_history: 'Histórico completo',
  financial_dashboard: 'Painel financeiro',
  paymentConfirmed: 'Pagamento confirmado',
  error_payment: 'Não foi possível registrar o pagamento',
  anonymous: 'Cliente',
  reception_operational: 'Operação da recepção',
  newClient: 'Novo cliente',
  anamnesis_form: 'Ficha de anamnese',
  scheduled: 'Agendados',
  checkins_done: 'Check-ins feitos',
  pending_payments: 'Pagamentos pendentes',
  expected_revenue: 'Receita prevista',
  filter: 'Filtro',
  receive: 'Receber',
  receive_payment: 'Receber pagamento',
  confirm_receipt_and_completion: 'Confirmar recebimento e concluir',
  searchPlaceholder: 'Buscar cliente por nome, telefone ou e-mail',
  registerNewClient: 'Cadastrar novo cliente',
  fullName: 'Nome completo',
  phone: 'Telefone',
  birthDate: 'Data de nascimento',
  allergies: 'Alergias',
  allergy: 'Alergia',
  notes: 'Observações',
  notesPlaceholder: 'Informações importantes sobre o cliente',
  saveClient: 'Salvar cliente',
  clientProfile: 'Perfil do cliente',
  personalData: 'Dados pessoais',
  history: 'Histórico',
  terms: 'Termos',
  documents: 'Documentos',
  contactInfo: 'Informações de contato',
  bodyMap: 'Mapa corporal',
  totalBookings: 'Total de agendamentos',
  totalSpent: 'Total gasto',
  noBookings: 'Nenhum agendamento encontrado',
  by: 'com',
  duration: 'duração',
  errorSavingAnamnesis: 'Não foi possível salvar a anamnese',
  newTerm: 'Novo termo',
  errorSavingTerm: 'Não foi possível salvar o termo',
  noConsentSigned: 'Nenhum termo assinado',
  consentTerm: 'Termo assinado',
  signedVia: 'Assinado via',
  device: 'dispositivo',
  printSave: 'Imprimir ou salvar',
  shareWhatsapp: 'Compartilhar no WhatsApp',
  fileTooLarge: 'Arquivo acima do limite permitido',
  attachFile: 'Anexar arquivo',
  noDocsAttached: 'Nenhum documento anexado',
  openDownload: 'Abrir documento',
  delete: 'Excluir',
  deleteClient: 'Excluir cliente',
  confirmDelete: 'Confirmar exclusão',
  close: 'Fechar',
  scheduleBooking: 'Agendar atendimento',
  scheduleBookingFor: 'Agendar para',
  select: 'Selecionar',
  time: 'Horario',
  durationHours: 'Duração em horas',
  projectDescription: 'Descrição do serviço',
  descriptionPlaceholder: 'Descreva o serviço combinado',
  totalValue: 'Valor total',
  deposit: 'Sinal',
  and: 'e',
  areRequired: 'são obrigatórios',
  hello: 'Olá',
  consentSignedSuccess: 'seu termo foi registrado com sucesso',
  on: 'em',
  anyQuestions: 'Se precisar de algo, estamos à disposição.',
  clientNoPhone: 'Cliente sem telefone cadastrado',
  errorDeletingClient: 'Não foi possível excluir o cliente',
  search: 'Buscar',
  quote_consultation: 'Orçamento',
  select_client: 'Selecione o cliente',
  select_term: 'Selecione',
  project_description: 'Descrição do serviço',
  estimated_value: 'Valor estimado',
  payment_method_deposit: 'Forma de pagamento',
  credit_card: 'Cartão de crédito',
  debit_card: 'Cartão de débito',
  cash: 'Dinheiro',
  confirm_booking: 'Salvar agendamento',
  new_quote: 'Novo orçamento',
  new_booking_title: 'Novo agendamento',
  edit_record: 'Editar registro',
  no_title: 'Serviço sem descrição',
  statusScheduled: 'Agendado',
  statusInProgress: 'Em andamento',
  statusCompleted: 'Concluído',
  statusCancelled: 'Cancelado',
  financial_result: 'Resultado financeiro',
  net_profit_history: 'Histórico do resultado líquido',
  revenue: 'Receita',
  expenses: 'Despesas',
  net_profit_accumulated: 'Lucro acumulado',
  vs_last_month: 'vs. mês anterior',
  cost_summary: 'Composição do resultado',
  operational_expenses: 'Despesas operacionais',
  final_profit: 'Lucro final',
  six_month_history: 'Histórico dos últimos 6 meses',
  full_name: 'Nome completo',
  what_is_your_name: 'Qual é o seu nome',
  describe_your_idea: 'Conte um pouco sobre o que você precisa',
  idea_placeholder: 'Descreva o serviço desejado, estilo, referências e observações',
  reference_image: 'Imagem de referência',
  tap_to_attach_photos: 'Toque para anexar fotos de referência',
  request_budget: 'Solicitar orçamento',
  request_budget_now: 'Solicite um orçamento rápido e receba o retorno da equipe',
  request_sent: 'Solicitação enviada',
  thanks: 'Obrigado',
  contact_soon_wa: 'Nossa equipe vai entrar em contato em breve pelo WhatsApp.',
  send_another: 'Enviar outra solicitacao',
  error_sending_request: 'Não foi possível enviar sua solicitação',
  confirm_payment_sim: 'Confirmar pagamento',
  payment_confirmed_msg: 'Pagamento confirmado com sucesso',
  finalize_payment: 'Finalizar pagamento',
  card: 'Cartao',
  scan_qr_to_pay: 'Escaneie o QR Code ou copie o código Pix para concluir o pagamento.',
  copied: 'Código copiado',
  card_number: 'Número do cartão',
  expiry: 'Validade',
  card_name: 'Nome impresso no cartao',
  as_on_card: 'Como está no cartão',
  transaction_secure_wa: 'Ambiente protegido para simulação de pagamento e confirmação de recebimento.',
  unified_daily_schedule: 'Agenda do dia',
  delayed_upper: 'Atrasado',
  unknown: 'Não informado',
  project: 'Serviço',
  clear: 'Limpar',
  save_signature: 'Salvar assinatura',
  payment_confirmed: 'Pagamento confirmado',
  confirm_payment: 'Confirmar pagamento',
};

function humanizeKey(key) {
  return key
    .replace(/([a-z])([A-Z])/g, '$1 $2')
    .replaceAll('_', ' ')
    .trim()
    .replace(/\s+/g, ' ')
    .replace(/^./, (char) => char.toUpperCase());
}

export const t = (key, niche = 'generic') => {
  const businessTerms = nicheTerms[niche] || nicheTerms.generic;
  return businessTerms[key] || baseTranslations[key] || humanizeKey(key);
};

export default nicheTerms;

